[workspace]
default-members = ["markdown-weaver", "markdown-weaver-escape"]
members = [
  "bench",
  "dos-fuzzer",
  "fuzz",
  "markdown-weaver",
  "markdown-weaver-escape",
]
resolver = "2"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
